name: CI
on:
  pull_request:
    paths:
      - Sources/**
      - Tests/**
      - .github/workflows/ci.yml
jobs:
  auto-cancel:
    runs-on: ubuntu-latest
    steps:
    - uses: technote-space/auto-cancel-redundant-job@v1

  linux:
    name: linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        swift:
        - 5.3
        - 5.4-focal  # Swift 5.4 requires llvm-cov v11
    container:
      image: swift:${{ matrix.swift }}
    steps:
    - uses: actions/checkout@v2
    - run: swift test --enable-code-coverage --parallel --enable-test-discovery

    - name: Generate Coverage Report
      run: |
        apt-get -qq update
        apt-get -qq install curl  # for codecov action 🙄
        b=$(swift build --show-bin-path)
        llvm-cov export \
          -format lcov \
          -instr-profile="$b"/codecov/default.profdata \
          --ignore-filename-regex='\.build/' \
          "$b"/*.xctest \
          > info.lcov
    - uses: codecov/codecov-action@v1
      with:
        file: ./info.lcov

  apple:
    runs-on: macos-latest
    strategy:
      matrix:
        dst:
          - platform=macOS
          - platform=tvOS Simulator,OS=latest,name=Apple TV
          - platform=iOS Simulator,OS=latest,name=iPhone 12
    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ^12
    - uses: actions/checkout@v2
    - uses: sersoft-gmbh/xcodebuild-action@v1
      with:
        spm-package: ./
        scheme: PromiseKit-Package
        destination: ${{ matrix.dst }}
        action: test
        enable-code-coverage: true
    - uses: codecov/codecov-action@v1

  watchOS:
    runs-on: macos-latest
    name: apple (watchOS)
    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ^12
    - uses: actions/checkout@v2
    # with Xcode 12.5 we can use the above matrix, but with 12.4
    # testing is not supported and trying to build with the Package.swift
    # tries to build the tests too 🙄
    - run: swift package generate-xcodeproj
    - uses: sersoft-gmbh/xcodebuild-action@v1
      with:
        project: PromiseKit.xcodeproj
        scheme: PromiseKit-Package
        destination: platform=watchOS Simulator,OS=latest,name=Apple Watch Series 5 - 40mm
        action: build

  lint:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - run: pod lib lint --fail-fast
